import PracticeTest from "../screens/PraticeTest/PraticeTest";

const screenName = {
    home: 'Home',
    profile: 'Profile',
    register: 'Register',
    login: 'Login',
    forgotPassword: 'ForgotPassword',
    setting: 'Setting',
    statistic: 'Statistic',
    privacy: 'Privacy',
    termAndCondition: 'TermAndCondition',
    signOut: 'SignOut',
    feedback: 'Feedback',
    share: 'Share',
    record: 'Record',
    notifycation: 'Notifycation',
    about: 'About',
    about_detail: 'AboutDetail',
    tips: 'Tip',
    tipDetail: 'TipDetail',
    tipContent: 'TipContent',
    practice: 'Practice',
    PracticeTest: 'PracticeTest',
    calendar: 'Calendar',
    introduce: 'Introduce',
    initStack: 'InitStack',
    lesson: 'Lesson',
    overview: 'Overview',
    reading: 'Reading',
    listening: 'Listening',
    writing: 'Writing',
    speaking: 'Speaking',
}
export default screenName;

